# Numerical and Scientific Computing

## <img src='https://az712634.vo.msecnd.net/notebooks/python_course/v1/flask.png' alt="Smiley face" width="42" height="42" align="left">Learning Objectives
* * *
<br>
* Become comfortable defining, slicing and assigment with numpy arrays (1D and multidimensional)
* Become familiar with boolean indexing
* See some examples of set logic
* Get started with some linear algebra in numpy

## What is `numpy` and what does it do?
* numerical python operating upon what is called an "ndarray"
* ndarrays are 1 to N dimensional arrays or vectors
* operations are quickly vectorized on ndarrays

### 1D arrays

In [ ]:
import numpy as np

# Here are three ways to create a 1D array in numpy
a = np.array([1, 2, 3, 4, 5])
a = np.array(range(1, 6))
a = np.arange(1, 6)

# what is a's type?  (use type(a))
# print a here...


<b>Slicing a 1D array</b>
* IMPORTANT: Slicing in NumPy does not return a copy, but rather what we call a <b>view</b>.
* If we modify the view, the original np array is <b>also modified</b>.
* If we truly want a copy we would use the `copy()` method.

<br>
Here's some proof that a <b>slice is a view for ndarrays</b> and changes to it will modify the original data:

In [ ]:
a = np.array([1, 2, 3, 4, 5])

# let's hold on to the original
a_orig = a.copy()

# A slice (3rd through 4th elements)
view = a[2:4]

# Reassignment
view[1] = 0

# What changed if anything?  print "a" and "a_orig"


<b>Assignment via slicing</b>

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a)

# Set 3rd through 4th elements to a scalar (note: indexing is not inclusive of the last index number)
a[2:4] = 0
print(a)

### 2D arrays

In [ ]:
a2d = np.array([range(5), range(5, 10), range(10, 15)])
print(a2d)

<b>Subscription</b>
* Two ways to access an element of 2D array

In [ ]:
# First way
x = a2d[0][3]
print(x)

# What do you think the second way is?  If you like R, this is familiar.  
# Write some code here...


In [ ]:
# Alternate subscription of 2D array

# This way
x = a2d[0, 3]
print(x)

# Or that
y = a2d[0, 3]
print(y)

<b>Using `reshape()`</b>
* Will conform a 1D array to an ND array

In [ ]:
# Instead of (to create one array containing three arrays)
a2d = np.array([range(5), range(5, 10), range(10, 15)])

# We could just do this
a2d = np.arange(15).reshape(3, 5)

a2d

In [ ]:
a2d = np.arange(0, 16).reshape(4, 4)

# We saw how to slice 1D arrays, e.g. a1d[1], now a2d[1] would be a 1D array

# If we want rows 2 and 3 we would use a range of indices
a2d[1:3]

In [ ]:
# What about column 4?
a2d[:, 3]

EXERCISE 1: Initializing and slicing 2D arrays
* Initialize a 3x4 2D array with all even numbers between 1 and 25 (HINT: use `arange`'s argument `step`)
```python
# e.g. Even numbers starting at 0 to 10
np.arange(0, 10, step = 2)
```
* Slice out the 1st and 3rd element in the 1st row

In [9]:
#### import numpy as np
aa = np.arange(0, 24, step = 2).reshape(3, 4)

print(aa)

a1 = aa[0,0]
a2 = aa[0,2]

print(a1)
print(a2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
0
4


### 3D arrays

In [10]:
# 2x2x5 array (explicitly initialized with literals)
a3d = np.array([[[1, 2, 3, 4, 5], 
                 [6, 7, 8, 9, 10]], 
                [[11, 12, 13, 14, 15], 
                 [16, 17, 18, 19, 20]]])
print(a3d)

# Or just do this
a3d = np.arange(1, 21).reshape(2, 2, 5)
print(a3d)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


EXERCISE 2: Slicing 3D arrays
* Use what you've seen about slicing 1D and 2D arrays to:
  1. Slice out the first 2D array from the above 3D array
  2. Slice out the second 1D from the first 2D array
  3. Slice out the third element in the second 1D array from the first 2D array

In [ ]:
# Code up your solution here...

### Indexing

<b>Boolean indexing</b>
* IMPORTANT: Boolean indexing creates a <b>copy</b> unlike slicing

In [11]:
# 7x4 2D array with some normally distributed random numbers
data = np.random.randn(7, 4)
print(data)

# Our boolean indexer
bindex = np.array([True, False, False, True, False, True, False])

# Are we slicing by rows or columns?

[[-0.66190205  0.43524405 -0.64344099  0.48079537]
 [ 0.21812405 -0.22458762  0.72115807  0.08594612]
 [-0.65541734 -2.31598609 -0.14487192 -0.19866791]
 [ 0.38053735  0.20396616 -1.53872685  0.54664777]
 [ 1.44493302  1.04215801 -0.79947441  0.49925188]
 [-0.88964217 -0.05176634 -0.237564    1.83548023]
 [ 0.09590703  1.79823438 -0.32528361  0.53886135]]


In [12]:
# let's slice with the boolean indexer now
data[bindex]

array([[-0.66190205,  0.43524405, -0.64344099,  0.48079537],
       [ 0.38053735,  0.20396616, -1.53872685,  0.54664777],
       [-0.88964217, -0.05176634, -0.237564  ,  1.83548023]])

In [ ]:
# How do you think you would reverse select with our boolean indexer?


# The answer is in solution to exercise 3

EXERCISE 3: Create a 2D boolean indexer and use it to slice a 2D array?
* Fill in the missing pieces to the following code to create this slicer.

Copy this code into a cell below and fill in
```python
# Exercise code - fill in the blank or missing parts below

import numpy as np

# 2x3 2D array with some normally distributed random numbers
data = np.random.___(2, 3)
print(data)

# our 2D boolean indexer
bindex = np.array([___]).reshape(2, 3)
print(bindex)

# Will it work?

# Also, apply the reverse of the boolean indexer to the data (check solution for this...)

```

In [ ]:
# Try your solution here

<b>Booleans to set a swath of values</b>

In [17]:
data = np.random.randn(7, 4)
print(data)
data[data < 0] = 0
print(data)

[[-0.87628603 -0.67921023 -1.44732309 -0.19048775]
 [-0.51234358  0.65806673  0.37507737 -0.34782281]
 [ 0.12846146  0.42762344  0.88573725  1.46667174]
 [-0.70336634 -0.73764451  0.34035867 -1.45085803]
 [-0.06278731 -0.48914432  0.16338974 -0.62033556]
 [ 0.52115107 -1.17836998  0.36557254 -1.23730749]
 [ 0.85357501 -1.20982168 -0.14507845 -0.44053336]]
[[ 0.          0.          0.          0.        ]
 [ 0.          0.65806673  0.37507737  0.        ]
 [ 0.12846146  0.42762344  0.88573725  1.46667174]
 [ 0.          0.          0.34035867  0.        ]
 [ 0.          0.          0.16338974  0.        ]
 [ 0.52115107  0.          0.36557254  0.        ]
 [ 0.85357501  0.          0.          0.        ]]


In [ ]:
# Set a whole row or set of rows to a scalar

# Our boolean indexer
bindex = np.array([True, False, False, True, False, True, False])

data[bindex] = 8
data

In [ ]:
# Show how would you set a whole column (or set of columns) to a value using a boolean indexer
bindex = np.array([True, False, False, True])
data[:, bindex] = 5
data

<b>Additional indexing options we are not going to cover</b>
* Fancy indexing
  1. Selecting out particular rows in a specified order
  2. Selecting elements corresponding to tuples of indices
  3. Use of `np.ix_` function to select a square region

### Transposing

In [20]:
# Initialize 2D array with some random integers between 1 and 5
data = np.random.randint(1, 6, size = 12).reshape(3, 4)
print(data)

dataT = data.T # could also use transpose() method
print(dataT)

[[5 4 4 5]
 [2 1 5 3]
 [3 5 3 1]]
[[5 2 3]
 [4 1 5]
 [4 5 3]
 [5 3 1]]


### Universal functions aka `ufuncs`

In [21]:
# 1D array
a = np.arange(10)
print(a)

# A couple of unary functions

sqroot = np.sqrt(a)
print(sqroot)

expon = np.exp(a)
print(expon)

[0 1 2 3 4 5 6 7 8 9]
[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.        ]
[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
   5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03
   2.98095799e+03   8.10308393e+03]


In [22]:
# let's make a couple of 1D arrays
a = np.random.randn(10)
b = np.random.randn(10)

# A couple of binary funcions

maxes = np.maximum(a, b)
print(maxes)

added = np.add(a, b)
print(added)

[ 0.12084804  0.45810096  2.07614612  1.41035342  0.01818937  0.95394762
  0.49944865  1.51769555  0.44348177  0.63710044]
[-0.78036151 -0.6062931   1.32807614  1.43459964  0.02368696  1.68146161
  0.96769657  1.42338475 -0.63496024 -0.72810124]


> For more information on available `ufuncs` visit the scipy/numpy docs [here](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).  Also, just note `numpy` uses the concept of <b>broadcasting</b> when performing operations (like `+ - * /` and `ufuncs`) on ndarrays to decide how to handle disparately shaped inputs.  More info [here](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#broadcasting).

### Conditional logic with `np.where`
* A great way to vectorize: `x if condition else y`
* In the following example, a boolean array (the condition), is used to choose an element either in the first 1D array or second 1D array.

In [23]:
# Two 1D arrays
a = np.arange(5)
b = np.arange(5, 10)

# A boolean indexer as the condition (decides from which 1D array to choose an element)
# i.e. if value is True - choose element from a, else choose element from b
cond = np.array([True, False, False, True, False])

In [24]:
# Old familiar way: list comprehension with our friendly zip function
result = [x if c else y for x, y, c in zip(a, b, cond)]
print(list(zip(a, b, cond)))
print(result)

# The better faster numpy way (especially for larger arrays!)
result = np.where(cond, a, b)
print(result)

# could cond be an anonymous function?  Try!

[(0, 5, True), (1, 6, False), (2, 7, False), (3, 8, True), (4, 9, False)]
[0, 6, 7, 3, 9]
[0 6 7 3 9]


### Some set logic for 1D arrays
* Functions to find unique elements, unions, intersections, set differences, symmetric set differences

<b>`np.unique()` will return a sorted, unique array</b>

In [25]:
a = ['a'] * 10
b = ['b'] * 12
c = ['c'] * 5
d = ['d'] * 8
ones = [1] * 20
z = ['z'] * 6

arr = z + a + d + c + b + ones
print(arr)

np.unique(arr)

# Compare to using set methods or operators learnt about previously


['z', 'z', 'z', 'z', 'z', 'z', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'c', 'c', 'c', 'c', 'c', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


array(['1', 'a', 'b', 'c', 'd', 'z'], 
      dtype='<U1')

<b>`np.intersect1d()` and `np.union1d()` will return sorted, unique intersection and union, respectively</b>

In [27]:
a = ['a'] * 10
b = ['b'] * 12
c = ['c'] * 5
d = ['d'] * 8

a1 = a + b + c
a2 = b + c + d

print(a1)
print(a2)
np.intersect1d(a1, a2)

# Show the union of a1 and a2...try this


['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'c', 'c', 'c', 'c', 'c']
['b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'c', 'c', 'c', 'c', 'c', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd']


array(['b', 'c'], 
      dtype='<U1')

EXERCISE 4:  Classic sets and ndarrays - a comparison exercise<br><br>
Using this array from above
```python
a = ['a'] * 100
b = ['b'] * 120
c = ['c'] * 50
d = ['d'] * 80
ones = [1] * 200
z = ['z'] * 60

arr = z + a + d + c + b + ones
```
Do the following:
* Create a classic set with it
* Sort it (HINT: you'll have to convert to a list of `str`)
* Convert it to an ndarray

For a fun bonus, compare an intersection using classic set methods versus numpy methods of the following two arrays:
```python
a1 = z + d + c + ones
a2 = a + d + b + ones
```

In [52]:
a = ['a'] * 100
b = ['b'] * 120
c = ['c'] * 50
d = ['d'] * 80
ones = [1] * 200
z = ['z'] * 60

arr = z + a + d + c + b + ones

ss = str(arr)

#ss.sort()
s2 = sorted(ss)
print(s2)
s2np = np.fromstring(s2,sep=',')
#print(s2np)

s2np.uni
#print(arr)
#strs = np.array_str(a)
#print(strs)


[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',

TypeError: a bytes-like object is required, not 'list'

### Sorting NumPy arrays
* Unlike built-in `sort()`, `np.sort()` does <b>not</b> sort inline
* Like built-in `sort()`, `np.sort()` can take a second argument indicating axis upon which to apply sort
* `np.sort()` sorts on rows by default

In [53]:
# 2D array
a2d = np.random.randn(4 , 3)
print(a2d)

a2dsort = np.sort(a2d)
print(a2dsort)

# np.sort() sorts on rows by default

# To sort on columns
a2dsort = np.sort(a2d, 0)
print(a2dsort)

[[-0.4866721  -1.27914902  0.4297186 ]
 [-0.58979334  0.20875754 -2.31901266]
 [-0.83484802 -0.38414837  0.26564855]
 [-0.37984836  0.46860004 -0.11797614]]
[[-1.27914902 -0.4866721   0.4297186 ]
 [-2.31901266 -0.58979334  0.20875754]
 [-0.83484802 -0.38414837  0.26564855]
 [-0.37984836 -0.11797614  0.46860004]]
[[-0.83484802 -1.27914902 -2.31901266]
 [-0.58979334 -0.38414837 -0.11797614]
 [-0.4866721   0.20875754  0.26564855]
 [-0.37984836  0.46860004  0.4297186 ]]


### Numpy and linear algebra

In [56]:
import numpy as np
# 2x3 array
x = np.array([[9., 3., 8.], [4., 7., 2.]])

# 3x2 array
y = np.array([[2., 4.], [-1, 9], [8, -5]])

print(x)
print(y)

# Two ways to get dot product (built-in vs. numpy way)
dot1 = x.dot(y)
dot2 = np.dot(x, y)

dot2

[[ 9.  3.  8.]
 [ 4.  7.  2.]]
[[ 2.  4.]
 [-1.  9.]
 [ 8. -5.]]


array([[ 79.,  23.],
       [ 17.,  69.]])

<b>Linear algebra library `numpy.linalg`</b>
* Like MATLAB and R, this library is (under the hood) implemented with Fortran libraries
* Also, this is just the very tip of the iceberg

In [57]:
from numpy.linalg import inv, eig

# let's take a numpy array and treat it like a matrix
X = np.random.randn(3, 3)
print('X:', X)

# Transpose
X = X.T
print('X.T:', X)

# Inverse matrix
Xi = inv(X)
print('X^-1:', Xi)

# Decomposition example: eigenvalues/eigenvectors
evalues, evectors = eig(X)
print('Eigenvalues: ', evalues)
print('Eigenvectors: ', evectors)

X: [[-0.1250224  -1.07270085  0.16441372]
 [-0.25888048  0.58638308  0.38259729]
 [-1.57040111 -0.37701943 -0.37070877]]
X.T: [[-0.1250224  -0.25888048 -1.57040111]
 [-1.07270085  0.58638308 -0.37701943]
 [ 0.16441372  0.38259729 -0.37070877]]
X^-1: [[-0.07914153 -0.75407212  1.10216918]
 [-0.49742622  0.32957343  1.7720193 ]
 [-0.54847872  0.00570286 -0.37986286]]
Eigenvalues:  [ 1.04730693+0.j         -0.47832751+0.80840184j -0.47832751-0.80840184j]
Eigenvectors:  [[ 0.44224325+0.j          0.69703638+0.j          0.69703638-0.j        ]
 [-0.87750571+0.j          0.52957722+0.25986362j  0.52957722-0.25986362j]
 [-0.18548486+0.j          0.06951683-0.40165478j  0.06951683+0.40165478j]]


<b>Use `help()` to see all that `numpy.linalg` has to offer

In [58]:
import numpy as np
help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

Created by a Microsoft Employee.
	
The MIT License (MIT)<br>
Copyright (c) 2016